NsNameDeletionRegexp: feature

Retention:
  Days: 1
  Hours: 2

DeletionBatchSize: 1
DeletionNapSeconds: 1

AnnotationKey: delete_after

IsUninstallReleases: true

PostoneNsDeletionByHelmDeploy: true

DeletionWindow:
  NotBefore: "00:00"
  NotAfter:  "23:59"
  WeekDays: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]

DryRun: true