NsNameDeletionRegexp: feature

Retention:
  Days: 7

DeletionBatchSize: 3
DeletionNapSeconds: 30

AnnotationKey: "delete_after"

IsUninstallReleases: true

PostoneNsDeletionByHelmDeploy: true

DeletionWindow:
  NotBefore: "07:00"
  NotAfter:  "23:59"
  WeekDays:  ["Sun", "Mon", "Tue", "Wed", "Fri", "Sat"]

DryRun: true



