NsNameDeletionRegexp: feature

Retention:
  Days: 7

DeletionBatchSize: 3
DeletionNapSeconds: 30

AnnotationKey: "delete_after"

IsUninstallReleases: true

PostoneNsDeletionByHelmDeploy: true

DeletionWindow:
  NotBefore: "15:05"
  NotAfter:  "16:10"
  WeekDays:  ["Sun", "Mon", "Tue", "Wed", "Fri", "Sat"]

DryRun: false



