NsNameDeletionRegexp: feature

retention:
  days: 1
  hours: 2

DeletionBatchSize: 1
DeletionNapSeconds: 1

AnnotationKey: delete_after

IsUninstallReleases: true

PostoneNsDeletionByHelmDeploy: true

DeletionWindow:
  NotBefore: "00:00"
  NotAfter:  "23:59"NsNameDeletionRegexp: feature

retention:
  days: 1
  hours: 2

DeletionBatchSize: 1
DeletionNapSeconds: 1

AnnotationKey: delete_after

IsUninstallReleases: true

PostoneNsDeletionByHelmDeploy: true

DeletionWindow:
  NotBefore: "00:00"
  NotAfter:  "23:59"