replicaCount: 1

image:
  imageName: reviewreaper:test
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: registrysecret


serviceAccount:
  create: true
  annotations: {}
  name: "reviewreaper"
  clusterRoleName: review-reaper

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
